/** Stable v1 paths published by the backend; transport remains opt-in. */
export const API_ROUTES = {
  csrf: '/api/v1/auth/csrf',
  organizationMembers: '/api/v1/organization/members',
  logout: '/api/v1/auth/logout',
  session: '/api/v1/session',
  accounts: '/api/v1/accounts',
  accountsWithOpening: '/api/v1/accounts/with-opening',
  cards: '/api/v1/cards',
  categories: '/api/v1/categories',
  people: '/api/v1/people',
  debts: '/api/v1/people/debt-positions',
  obligations: '/api/v1/obligations',
  investments: '/api/v1/investments',
  movementKinds: '/api/v1/movement-kinds',
  movementSearch: '/api/v1/movements/search',
  movements: '/api/v1/movements',
  transfers: '/api/v1/operations/transfers',
  cardPayments: '/api/v1/operations/card-payments',
  preferences: '/api/v1/preferences',
  featureFlags: '/api/v1/feature-flags',
  notifications: '/api/v1/notifications',
  audit: '/api/v1/admin/audit',
  adminUsers: '/api/v1/superadmin/users',
  adminRoles: '/api/v1/superadmin/roles',
  adminErrors: '/api/v1/superadmin/errors',
  superAdminCapabilities: '/api/v1/superadmin/capabilities',
  superAdminPermissions: '/api/v1/superadmin/permissions',
  superAdminFeatureFlags: '/api/v1/superadmin/feature-flags',
  superAdminAudit: '/api/v1/superadmin/audit',
  recurrences: '/api/v1/recurrences',
  projectedCalendar: '/api/v1/calendar/projected',
  sharedPurchases: '/api/v1/shared-purchases',
  settlements: '/api/v1/settlements',
  cardStatus: (id: string) => `/api/v1/cards/${encodeURIComponent(id)}/status`,
  notificationRead: (id: string) => `/api/v1/notifications/${encodeURIComponent(id)}/read`,
  recurrenceMaterializations: (id: string) => `/api/v1/recurrences/${encodeURIComponent(id)}/materializations`,
  adminFeatureFlag: (key: string) => `/api/v1/admin/feature-flags/${encodeURIComponent(key)}`,
  adminUserActive: (id: string) => `/api/v1/superadmin/users/${encodeURIComponent(id)}/active`,
  adminUserCapability: (id: string) => `/api/v1/superadmin/users/${encodeURIComponent(id)}/capability-override`,
  adminUserRoles: (id: string) => `/api/v1/superadmin/users/${encodeURIComponent(id)}/roles`,
  adminRole: (id: string) => `/api/v1/superadmin/roles/${encodeURIComponent(id)}`,
  adminRoleActive: (id: string) => `/api/v1/superadmin/roles/${encodeURIComponent(id)}/active`,
  adminError: (id: string) => `/api/v1/superadmin/errors/${encodeURIComponent(id)}`,
  superAdminFeatureFlag: (key: string) => `/api/v1/superadmin/feature-flags/${encodeURIComponent(key)}`,
  movement: (id: string) => `/api/v1/movements/${encodeURIComponent(id)}`,
  movementClassification: (id: string) => `/api/v1/movements/${encodeURIComponent(id)}/classification`,
  movementReversal: (id: string) => `/api/v1/movements/${encodeURIComponent(id)}/reversal`,
  account: (id: string) => `/api/v1/accounts/${encodeURIComponent(id)}`,
  dashboard: '/api/v1/dashboard',
  openApi: '/openapi/v1.json',
} as const;
