import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';
import { NgIcon, provideIcons } from '@ng-icons/core';
import {
  lucideArrowDown,
  lucideArrowLeftRight,
  lucideArrowUp,
  lucideArrowUpDown,
  lucideColumns3,
  lucideListFilter,
  lucideBanknote,
  lucideBell,
  lucideBriefcase,
  lucideBuilding2,
  lucideCalendar,
  lucideCar,
  lucideChartColumn,
  lucideChartPie,
  lucideCheck,
  lucideChevronDown,
  lucideChevronLeft,
  lucideChevronRight,
  lucideChevronUp,
  lucideChevronsLeft,
  lucideChevronsRight,
  lucideClock,
  lucideCreditCard,
  lucideDownload,
  lucideEllipsis,
  lucideFilm,
  lucideFlag,
  lucideGift,
  lucideGraduationCap,
  lucideGripHorizontal,
  lucideGripVertical,
  lucideHeartPulse,
  lucideHouse,
  lucideInfo,
  lucideLandmark,
  lucideLayers,
  lucideLayoutDashboard,
  lucideLightbulb,
  lucideList,
  lucideMenu,
  lucidePause,
  lucidePencil,
  lucidePercent,
  lucidePiggyBank,
  lucidePlane,
  lucidePlay,
  lucidePlus,
  lucideRepeat,
  lucideRotateCcw,
  lucideSearch,
  lucideShield,
  lucideShoppingCart,
  lucideSlidersHorizontal,
  lucideTag,
  lucideTarget,
  lucideTrash2,
  lucideTrendingDown,
  lucideTrendingUp,
  lucideTriangleAlert,
  lucideUsers,
  lucideUtensils,
  lucideWallet,
  lucideX,
} from '@ng-icons/lucide';

const ICONOS = {
  dashboard: 'lucideLayoutDashboard',
  movements: 'lucideArrowLeftRight',
  calendar: 'lucideCalendar',
  accounts: 'lucideCreditCard',
  people: 'lucideUsers',
  portfolio: 'lucideChartPie',
  planning: 'lucideTarget',
  reports: 'lucideChartColumn',
  notifications: 'lucideBell',
  admin: 'lucideShield',
  settings: 'lucideSlidersHorizontal',
  trendUp: 'lucideTrendingUp',
  trendDown: 'lucideTrendingDown',
  wallet: 'lucideWallet',
  clock: 'lucideClock',
  percent: 'lucidePercent',
  tag: 'lucideTag',
  menu: 'lucideMenu',
  close: 'lucideX',
  search: 'lucideSearch',
  plus: 'lucidePlus',
  download: 'lucideDownload',
  organization: 'lucideBuilding2',
  more: 'lucideEllipsis',
  chevronDown: 'lucideChevronDown',
  chevronUp: 'lucideChevronUp',
  edit: 'lucidePencil',
  flag: 'lucideFlag',
  list: 'lucideList',
  shield: 'lucideShield',
  trash: 'lucideTrash2',
  pause: 'lucidePause',
  play: 'lucidePlay',
  grip: 'lucideGripVertical',
  first: 'lucideChevronsLeft',
  previous: 'lucideChevronLeft',
  next: 'lucideChevronRight',
  last: 'lucideChevronsRight',
  check: 'lucideCheck',
  info: 'lucideInfo',
  warning: 'lucideTriangleAlert',
  undo: 'lucideRotateCcw',
  layers: 'lucideLayers',
  gripHorizontal: 'lucideGripHorizontal',
  columns: 'lucideColumns3',
  filter: 'lucideListFilter',
  sortAscending: 'lucideArrowUp',
  sortDescending: 'lucideArrowDown',
  sortNone: 'lucideArrowUpDown',
  utensils: 'lucideUtensils',
  car: 'lucideCar',
  home: 'lucideHouse',
  cart: 'lucideShoppingCart',
  health: 'lucideHeartPulse',
  education: 'lucideGraduationCap',
  travel: 'lucidePlane',
  leisure: 'lucideFilm',
  utilities: 'lucideLightbulb',
  work: 'lucideBriefcase',
  gift: 'lucideGift',
  savings: 'lucidePiggyBank',
  cash: 'lucideBanknote',
  bank: 'lucideLandmark',
  repeat: 'lucideRepeat',
  users: 'lucideUsers',
} as const;

export type IconName = keyof typeof ICONOS;

const REGISTRO = {
  lucideArrowDown,
  lucideArrowLeftRight,
  lucideArrowUp,
  lucideArrowUpDown,
  lucideColumns3,
  lucideListFilter,
  lucideBanknote,
  lucideBell,
  lucideBriefcase,
  lucideBuilding2,
  lucideCalendar,
  lucideCar,
  lucideChartColumn,
  lucideChartPie,
  lucideCheck,
  lucideChevronDown,
  lucideChevronLeft,
  lucideChevronRight,
  lucideChevronUp,
  lucideChevronsLeft,
  lucideChevronsRight,
  lucideClock,
  lucideCreditCard,
  lucideDownload,
  lucideEllipsis,
  lucideFilm,
  lucideFlag,
  lucideGift,
  lucideGraduationCap,
  lucideGripHorizontal,
  lucideGripVertical,
  lucideHeartPulse,
  lucideHouse,
  lucideInfo,
  lucideLandmark,
  lucideLayers,
  lucideLayoutDashboard,
  lucideLightbulb,
  lucideList,
  lucideMenu,
  lucidePause,
  lucidePencil,
  lucidePercent,
  lucidePiggyBank,
  lucidePlane,
  lucidePlay,
  lucidePlus,
  lucideRepeat,
  lucideRotateCcw,
  lucideSearch,
  lucideShield,
  lucideShoppingCart,
  lucideSlidersHorizontal,
  lucideTag,
  lucideTarget,
  lucideTrash2,
  lucideTrendingDown,
  lucideTrendingUp,
  lucideTriangleAlert,
  lucideUsers,
  lucideUtensils,
  lucideWallet,
  lucideX,
};

const ICONOS_POR_NOMBRE: Readonly<Record<string, string>> = ICONOS;

@Component({
  selector: 'fin-icon',
  imports: [NgIcon],
  viewProviders: [provideIcons(REGISTRO)],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: 'inline-flex size-[var(--icon-size,1.15em)] flex-none', 'aria-hidden': 'true' },
  template: `@if (icono(); as nombre) {
    <ng-icon [name]="nombre" size="100%" strokeWidth="1.75" />
  }`,
})
export class IconComponent {
  readonly name = input.required<string>();
  readonly icono = computed(() => ICONOS_POR_NOMBRE[this.name()] ?? '');
}
