import { P } from '../../core/session/permissions';
import { I18nService } from '../../core/i18n';
import { Widget } from './dashboard.model';

export function buildWidgetCatalog(i18n: I18nService): Widget[] {
  return [
    {
      id: 'flow',
      title: i18n.t('dashboard.widget.flow.title'),
      kicker: i18n.t('dashboard.widget.flow.kicker'),
      type: 'flow',
      wide: true,
      capability: P.dashboard.widget.flujo,
    },
    {
      id: 'categories',
      title: i18n.t('dashboard.widget.categories.title'),
      kicker: i18n.t('dashboard.widget.categories.kicker'),
      type: 'categories',
      wide: false,
      capability: P.dashboard.widget.categorias,
    },
    {
      id: 'accounts',
      title: i18n.t('dashboard.widget.accounts.title'),
      kicker: i18n.t('dashboard.widget.accounts.kicker'),
      type: 'accounts',
      wide: false,
      capability: P.dashboard.widget.cuentas,
    },
    {
      id: 'trend',
      title: i18n.t('dashboard.widget.trend.title'),
      kicker: i18n.t('dashboard.widget.trend.kicker'),
      type: 'trend',
      wide: true,
      capability: P.dashboard.widget.tendencia,
    },
    {
      /*
       * Antes tenia `type: 'accounts'`, el mismo tipo que el widget "accounts" de arriba:
       * ambos caian en el mismo @case del template y mostraban exactamente lo mismo. Con
       * el motor generico cada widget trae su propia dimension/medida.
       */
      id: 'commitments',
      title: i18n.t('dashboard.widget.commitments.title'),
      kicker: i18n.t('dashboard.widget.commitments.kicker'),
      type: 'bar',
      dimension: 'account',
      measure: 'amount',
      wide: false,
      capability: P.dashboard.widget.compromisos,
    },
    {
      // Mismo caso que "commitments": tenia `type: 'categories'`, duplicando ese widget.
      id: 'health',
      title: i18n.t('dashboard.widget.health.title'),
      kicker: i18n.t('dashboard.widget.health.kicker'),
      type: 'bar',
      dimension: 'category',
      measure: 'average',
      wide: false,
      capability: P.dashboard.widget.salud,
    },
    /*
     * Galería: un widget por cada tipo de grafica que el motor sabe dibujar, para que el
     * usuario de prueba vea de un vistazo todo el catalogo (genericos + fijos) sin tener
     * que abrir "Crear widget" veinte veces. Sin `capability` -heredan
     * `dashboard.widget.propios`, igual que cualquier widget que alguien cree a mano.
     */
    {
      id: 'g-line',
      title: i18n.t('dashboard.widget.gallery.line.title'),
      kicker: i18n.t('dashboard.widget.gallery.kicker'),
      type: 'line',
      dimension: 'date',
      measure: 'income',
      wide: false,
    },
    {
      id: 'g-area',
      title: i18n.t('dashboard.widget.gallery.area.title'),
      kicker: i18n.t('dashboard.widget.gallery.kicker'),
      type: 'area',
      dimension: 'date',
      measure: 'expense',
      wide: false,
    },
    {
      id: 'g-barh',
      title: i18n.t('dashboard.widget.gallery.barH.title'),
      kicker: i18n.t('dashboard.widget.gallery.kicker'),
      type: 'barH',
      dimension: 'category',
      measure: 'count',
      wide: false,
    },
    {
      id: 'g-grouped',
      title: i18n.t('dashboard.widget.gallery.grouped.title'),
      kicker: i18n.t('dashboard.widget.gallery.kicker'),
      type: 'grouped',
      dimension: 'category',
      dimension2: 'kind',
      measure: 'amount',
      wide: true,
    },
    {
      id: 'g-stacked-bars',
      title: i18n.t('dashboard.widget.gallery.stackedBars.title'),
      kicker: i18n.t('dashboard.widget.gallery.kicker'),
      type: 'stackedBars',
      dimension: 'account',
      dimension2: 'kind',
      measure: 'amount',
      wide: true,
    },
    {
      id: 'g-stacked100',
      title: i18n.t('dashboard.widget.gallery.stacked100.title'),
      kicker: i18n.t('dashboard.widget.gallery.kicker'),
      type: 'stacked100',
      dimension: 'category',
      dimension2: 'kind',
      measure: 'count',
      wide: true,
    },
    {
      id: 'g-pie',
      title: i18n.t('dashboard.widget.gallery.pie.title'),
      kicker: i18n.t('dashboard.widget.gallery.kicker'),
      type: 'pie',
      dimension: 'account',
      measure: 'count',
      wide: false,
    },
    {
      id: 'g-treemap',
      title: i18n.t('dashboard.widget.gallery.treemap.title'),
      kicker: i18n.t('dashboard.widget.gallery.kicker'),
      type: 'treemap',
      dimension: 'category',
      measure: 'expense',
      wide: false,
    },
    {
      id: 'g-funnel',
      title: i18n.t('dashboard.widget.gallery.funnel.title'),
      kicker: i18n.t('dashboard.widget.gallery.kicker'),
      type: 'funnel',
      dimension: 'category',
      measure: 'expense',
      wide: false,
    },
    {
      id: 'g-waterfall',
      title: i18n.t('dashboard.widget.gallery.waterfall.title'),
      kicker: i18n.t('dashboard.widget.gallery.kicker'),
      type: 'waterfall',
      dimension: 'date',
      measure: 'amount',
      wide: true,
    },
    {
      id: 'g-card',
      title: i18n.t('dashboard.widget.gallery.card.title'),
      kicker: i18n.t('dashboard.widget.gallery.kicker'),
      type: 'card',
      measure: 'income',
      wide: false,
    },
    {
      id: 'g-matrix',
      title: i18n.t('dashboard.widget.gallery.matrix.title'),
      kicker: i18n.t('dashboard.widget.gallery.kicker'),
      type: 'matrix',
      dimension: 'category',
      dimension2: 'kind',
      measure: 'count',
      wide: true,
    },
    {
      id: 'g-table',
      title: i18n.t('dashboard.widget.gallery.table.title'),
      kicker: i18n.t('dashboard.widget.gallery.kicker'),
      type: 'table',
      dimension: 'person',
      measure: 'amount',
      wide: false,
    },
    {
      id: 'g-indicator',
      title: i18n.t('dashboard.widget.gallery.indicator.title'),
      kicker: i18n.t('dashboard.widget.gallery.kicker'),
      type: 'indicator',
      measure: 'expense',
      goalMin: 0,
      goalTarget: 3000000,
      goalMax: 5000000,
      wide: false,
    },
    {
      id: 'g-scatter',
      title: i18n.t('dashboard.widget.gallery.scatter.title'),
      kicker: i18n.t('dashboard.widget.gallery.kicker'),
      type: 'scatter',
      wide: true,
    },
    {
      id: 'g-donut',
      title: i18n.t('dashboard.widget.gallery.donut.title'),
      kicker: i18n.t('dashboard.widget.gallery.kicker'),
      type: 'donut',
      wide: false,
    },
    {
      id: 'g-stacked',
      title: i18n.t('dashboard.widget.gallery.stacked.title'),
      kicker: i18n.t('dashboard.widget.gallery.kicker'),
      type: 'stacked',
      wide: true,
    },
    {
      id: 'g-heatmap',
      title: i18n.t('dashboard.widget.gallery.heatmap.title'),
      kicker: i18n.t('dashboard.widget.gallery.kicker'),
      type: 'heatmap',
      wide: true,
    },
    {
      id: 'g-gauge',
      title: i18n.t('dashboard.widget.gallery.gauge.title'),
      kicker: i18n.t('dashboard.widget.gallery.kicker'),
      type: 'gauge',
      wide: false,
    },
    {
      id: 'g-histogram',
      title: i18n.t('dashboard.widget.gallery.histogram.title'),
      kicker: i18n.t('dashboard.widget.gallery.kicker'),
      type: 'histogram',
      wide: false,
    },
    {
      id: 'g-colorscale',
      title: i18n.t('dashboard.widget.gallery.colorScale.title'),
      kicker: i18n.t('dashboard.widget.gallery.kicker'),
      type: 'colorScale',
      measure: 'expense',
      goalMin: 0,
      goalTarget: 3000000,
      goalMax: 5000000,
      wide: false,
    },
    {
      id: 'g-statusbars',
      title: i18n.t('dashboard.widget.gallery.statusBars.title'),
      kicker: i18n.t('dashboard.widget.gallery.kicker'),
      type: 'statusBars',
      dimension: 'category',
      measure: 'expense',
      wide: false,
    },
  ];
}
